apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: auth-backend
  template:
    metadata:
      labels:
        app: auth-backend
    spec:
      imagePullSecrets:
        - name: j11er-docker-registry
      initContainers:
        - name: migrations
          image: {{ .Values.app.image.tag }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: auth-backend-env-config
          command: ["/bin/sh"]
          args: ["/opt/scripts/run-migrations.sh"]
          volumeMounts:
            - name: bash-script-migrations
              mountPath: /opt/scripts/
              subPath: run-migrations.sh
      containers:
        - name: auth-backend
          image: {{ .Values.app.image.tag }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: auth-backend-env-config
          ports:
            - name: grpc
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
          - name: bash-script-migrations
            configMap:
              name: bash-script-migrations
