apiVersion: v1
kind: Service
metadata:
  name: auth-backend-service
  labels:
    name: auth-backend-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
  selector:
    app: auth-backend
